# For more information, see: http://docs.haskellstack.org/en/stable/yaml_configuration.html

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: nightly-2016-04-05

# Local packages, usually specified by relative directory name
packages:
- '.'
- location:
    git: git@bitbucket.org:pdedecker/simplejsonserver.git
    commit: c458b082dcb69d300c9d858dbb88addaffb9f194
- location:
    git: git@bitbucket.org:pdedecker/hsoceanoptics.git
    commit: d5449342500fe33fdcad019dd67b97eae42f7cdb
- location:
    git: git@bitbucket.org:pdedecker/hsgpio.git
    commit: 27c7f434aaf03807b681a85cf24db06172e26496

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 1.0.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
